### PR TITLE
Modification to oversize system - fix for single-sheet users

### PR DESCRIPTION
**Pull request by Loufe**
Hi Alex,

This rewrite allows permits using a single-sheet setup with the new oversize data. Otherwise only oversize animation tiles are created. 

Let me know what you think.

### CODE REVIEW

**Comment by alextrevisan** [comment]
Not every slash is oversized, take this as example: https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Dagger_dagger&sex=male

**Comment by Loufe** [comment]
> Not every slash is oversized, take this as example: https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Dagger_dagger&sex=male
> 

I'm not quite sure I follow your point with the oversize... this PR code has all the regular-size slash/thurst/whip. The AddIfOversized function will return the normal sized one if the enum is not that _specific oversized animation_. I might be missing something here, please let me know.

> Others like rod have a very different animation with the base character, with for example 13 frames, and I don't know yet how to do it: https://sanderfrenken.github.io/Universal-LPC-Spritesheet-Character-Generator/#?body=Body_color_light&head=Human_male_light&weapon=Rod_rod&sex=male

I'm not sure I follow, is this a component-animation problem? The flattened sheet I have would work just fine with the way the code is written for the rod, from what I can tell. Again, I may be misunderstanding, could you expand on that?

**Comment by alextrevisan** [comment]
With this aproach you add all animations to all spritesheet, so my sword_slash spritesheet, that is oversized now have CAST_RIGHT, that has the same animation as SLASH_RIGHT. If I call LPC->play(CAST_RIGHT) the animation of the player is correct but the sword will animate CAST_RIGHT, that in this case is SLASH_RIGHT

**Comment by Loufe** [comment]
@alextrevisan I think I understand what you mean. Out of curiosity, what's your long-term vision for the merging of sheets? Just thinking about your issue, https://github.com/alextrevisan/LPCAnimatedSprite2D/issues/13 . If that were implemented, this approach would be ok, then?

**Comment by Loufe** [comment]
Following discussions today, closing and using a different approach.

**Pull request closed without merging**
