### PR TITLE
Add icon to the nodes

### PR DESCRIPTION
**Pull request by alextrevisan**
Just added icons to the nodes

image

https://github.com/alextrevisan/LPCAnimatedSprite2D/issues/29

### CODE REVIEW

**Comment by Loufe** [comment]
Maybe we could have a bit of text with "2D" and "3D" in the icon?

**Comment by alextrevisan** [comment]
> Maybe we could have a bit of text with "2D" and "3D" in the icon?

I have no ideia how it could be. Do you have any idea?

**Comment by alextrevisan** [comment]
Maybe the colors can change, like the Node2D and Node3D?

**Comment by Loufe** [comment]
Maybe we could just do a blue background behind the head for 2D and red for 3D, like the Node2D and Node3D icons?

**Comment by alextrevisan** [comment]
Like this?

image

**Comment by Loufe** [comment]
Exactly what I had in mind, they look great!

**Pull request merged**
